### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FireHeat7** [ManaNet/mana-issues#2]
I keep putting in * (the set prefix) then yuriverse bind or even waifuworld bind yet nothing is working, so i am not sure

**To Reproduce**

**Expected behavior**
I expected to get hourly pictures on my server but with no luck, i even tried kicking the mana bot and reinviting it, but still nothing

**Screenshots**

**Additional context**

**Comment by ShindouMihou** [comment]
Hello, thanks for reporting. I can't seem to reproduce the issue since everything is working on my side. Are you sure the bot has permissions to send messages or some sort on the channel you were sending on?

![Screenshot_2021-05-23-05-38-31-85.jpg](https://user-images.githubusercontent.com/69381903/119241529-ababaa80-bb89-11eb-9314-081a6e003112.jpg)

![Screenshot_2021-05-23-05-38-59-83.jpg](https://user-images.githubusercontent.com/69381903/119241530-af3f3180-bb89-11eb-8825-9e505faa9f3c.jpg)

You can try pinging Mana to see if the prefix is wrong and also you can try  `Mana.prefix set pa.` to change the prefix back.

![Screenshot_2021-05-23-05-39-16-20.jpg](https://user-images.githubusercontent.com/69381903/119241522-9a629e00-bb89-11eb-86ff-e3b627def564.jpg)
